services:
  aqua:
    image: liuuner/aqua:0.0.2
#    environment:
#        - "DATABASE_URL=/data/aqua.db"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.aqua.loadbalancer.server.port=8080"
      - "traefik.http.routers.aqua.rule=Host(`aqua.liuuner.ch`)"
      - "traefik.http.routers.aqua.entrypoints=websecure"
      - "traefik.http.routers.aqua.tls.certresolver=letsencrypt"
    restart: unless-stopped
    volumes:
        - aqua:/data
    depends_on:
      - traefik
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 5s
#    deploy:
#      replicas: 1
#      update_config:
#        order: start-first

volumes:
  aqua: